### ISSUE TITLE
Add support for Redis requirepass

### ISSUE THREAD

**Issue by erik-dekker** [Icinga/puppet-icingadb#4]
**Current behaviour**
When Icingaweb2 runs on a dedicated host separated from IcingaDB, it needs to connect to the Redis instance located on the IcingaDB instance. Since Redis uses protected mode by default for incoming connections not originating from 127.0.0.1, it requires password authentication.

Currently this module does not support the `requirepass` feature to setup a password. Therefore, Icingaweb2 cannot connect to Redis and won't work.

**Suggested solution**
`requirepass` is already configurable by the puppet-redis module. We just need to pass through an extra parameter.

**Comment by lbetz** [comment]
Right, the whole code fpr the icingadb is based on RC1 (one and a half year ago).

For the release work started in branch 'release'.

**Comment by erik-dekker** [comment]
Ah yeah, I noticed that and started to work on this today too based on your master branch. After looking at your release branch I see we kinda did the same.. :) Although your branch looks a little more progressed. What are you still working on, need some help?

**Comment by lbetz** [comment]
Hi Erik,

help is very welcome of course. At the moment I am not sure how to implement the tls support. The tls for icingadb service itself and the client certs for connection to redis and the database. And the icingadb-redis service of course.

In icinga2 and icingaweb2 it's possible to manage the certificate and key content, but I am not happy with the code and parameterization ... Ideas very welcome.

Bye
Lennart

**Comment by lbetz** [comment]
coming in v1.0.0
